module.exports = {
  name: "Javier",
  url: "https://www.javierfuente.com",
  portfolioUrl: "https://javman18.github.io/",
  goatcounter: "https://javierfuente.goatcounter.com/count",
  giscus: {
    repo: "javman18/javier-blog",
    repoId: "R_kgDOQ6GC4A",
    category: "Announcements",
    categoryId: "DIC_kwDOQ6GC4M4C505T",
  },
  buttondown: {
    action: "https://buttondown.com/api/emails/embed-subscribe/fuente",
    referUrl: "https://buttondown.com/refer/fuente",
  },
  strings: {
    es: {
      subtitle: "escritura · implante · vida diaria",
      lede: "Un espacio personal para escribir con honestidad. Fragmentos del libro, notas del implante, cosas del trabajo y lo cotidiano.",
      navAria: "Secciones",
      portfolio: "Portafolio",
      featuredTitle: "Destacados",
      featuredSub: "Para empezar rápido",
      recentTitle: "Recientes",
      recentSub: "Últimas publicaciones",
      archiveTitle: "Archivo",
      archiveSub: "Explora por tema",
      readMore: "Leer →",
      backHome: "← Volver al inicio",
      comments: "Comentarios",
      commentsSub: "¿Qué piensas? Deja un comentario o cuéntame qué te gustaría leer.",
      subscribeTitle: "Suscríbete",
      subscribeSub: "Un correo cuando publique algo nuevo. Nada más.",
      subscribeLabel: "Tu correo",
      subscribeButton: "Suscribirme",
      subscribePowered: "Impulsado por Buttondown",
      workCv: "Trabajo profesional y CV →",
    },
    en: {
      subtitle: "writing · implant · daily life",
      lede: "A personal space to write honestly. Book excerpts, notes about the implant, work-related thoughts, and everyday life.",
      navAria: "Sections",
      portfolio: "Portfolio",
      featuredTitle: "Featured",
      featuredSub: "A good place to start",
      recentTitle: "Recent",
      recentSub: "Latest posts",
      archiveTitle: "Archive",
      archiveSub: "Browse by topic",
      readMore: "Read →",
      backHome: "← Back to home",
      comments: "Comments",
      commentsSub: "What do you think? Leave a comment or tell me what you'd like to read.",
      subscribeTitle: "Subscribe",
      subscribeSub: "An email when I publish something new. That's it.",
      subscribeLabel: "Your email",
      subscribeButton: "Subscribe",
      subscribePowered: "Powered by Buttondown",
      workCv: "Professional work and CV →",
    },
  },
};
