module.exports = {
  name: "Javier",
  portfolioUrl: "https://javman18.github.io/",
  goatcounter: "https://javierfuente.goatcounter.com/count",
  giscus: {
    repo: "javman18/javier-blog",
    repoId: "R_kgDOQ6GC4A",
    category: "Announcements",
    categoryId: "DIC_kwDOQ6GC4M4C505T",
  },
  strings: {
    es: {
      subtitle: "escritura · implante · vida diaria",
      lede: "Un espacio personal para escribir con honestidad. Fragmentos del libro, notas del implante, cosas del trabajo y lo cotidiano.",
      navAria: "Secciones",
      portfolio: "Portafolio",
      featuredTitle: "Destacados",
      featuredSub: "Para empezar rápido",
      recentTitle: "Recientes",
      recentSub: "Últimas publicaciones",
      archiveTitle: "Archivo",
      archiveSub: "Explora por tema",
      readMore: "Leer →",
      backHome: "← Volver al inicio",
      comments: "Comentarios",
      workCv: "Trabajo profesional y CV →",
    },
    en: {
      subtitle: "writing · implant · daily life",
      lede: "A personal space to write honestly. Book excerpts, notes about the implant, work-related thoughts, and everyday life.",
      navAria: "Sections",
      portfolio: "Portfolio",
      featuredTitle: "Featured",
      featuredSub: "A good place to start",
      recentTitle: "Recent",
      recentSub: "Latest posts",
      archiveTitle: "Archive",
      archiveSub: "Browse by topic",
      readMore: "Read →",
      backHome: "← Back to home",
      comments: "Comments",
      workCv: "Professional work and CV →",
    },
  },
};
